name = "backend"
main = "src/index.ts"
compatibility_date = "2024-10-28"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[vars]
 DATABASE_URL = "prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMTBmZDEzM2UtZGY1MS00NGNlLTgzNmEtMjg2MWQyYTJmNTEwIiwidGVuYW50X2lkIjoiMmNmYTFhODZjNWM0OGVjM2FjZTI1MGU4YWQ0YTI0NzRmZDMzMWIzMTdjMjg1MTVhN2M2NTg0ZDkxMmVhOTQ0MyIsImludGVybmFsX3NlY3JldCI6IjQ4NWJlNzQ4LWE5MjYtNDAzYi1iYjRhLWYxZTJjOGQ4NTg4MyJ9.toN1_B-hn_ZXTw3ja8I8kIXxOqIkyIuC5mJhk___H18"
 JWT_SECRET = "shinraTensei"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1